services:
  test-fastapi:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    container_name: test_api_service
    command: >
      sh -c "pytest"
    environment:
      APP_CONFIG__DB__URL: "postgresql+asyncpg://test_user:test_pass@test-db:5432/test_db"
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - test_service_network

  test-db:
    image: postgres:16
    container_name: test_qna_db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "6271:5432"
    networks:
      - test_service_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_postgres_data:

networks:
  test_service_network:
    driver: bridge
